name: CI Tests

on:
  pull_request: {}
  push:
    branches: ['main', 'dev']
  workflow_dispatch: {}

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run tests
        run: |
          cd backend
          pnpm hardhat test
