name: CI Tests

on:
  pull_request: {}
  push:
    branches: ['main', 'dev']
  workflow_dispatch: {}

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-hardhat:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run tests with coverage
        run: |
          cd backend
          pnpm hardhat coverage

      - name: Code coverage at 100%
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: './backend/coverage/lcov.info'
          min_coverage: 100

  tests-foundry:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          cd backend
          forge --version
          forge build --sizes

      - name: Run Forge tests
        run: |
          cd backend
          forge coverage -vvv --report lcov

      - name: Code coverage at 100%
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: './backend/lcov.info'
          min_coverage: 100
