name: CI Tests

on:
  pull_request: {}
  push:
    branches: ['main', 'dev']
  workflow_dispatch: {}

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run tests with coverage
        run: |
          cd backend
          pnpm hardhat coverage
